# Site settings
title: Mursal Kakar
description: Personal website & blog
author: Mursal Kakar
email: Mursalmkakar@gmail.com

baseurl: "/"  # Since you're deploying to root
url: "https://mursalmkakar.github.io"

theme: minima

github_username: Mursalmkakar

# Plugins
plugins:
  - jekyll-feed

# Navigation bar (optional, if your layout supports it)
#nav:
    # - title: Blog
    #  url: /blog/

# Exclude from processing (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

#Page design 
# _config.yml
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default

include:
  - docs/assets/css/style.css
